swagger: "2.0"
info:
  title: Quote API
  description: API description in Markdown.
  version: 1.0.0
host: quote-api.apigateway.ramnetquote.cloud.goog
basePath: /v1
schemes:
  - https
paths:
  /data:
    get:
      summary: Get data from Firestore.
      operationId: "getData"
      x-google-backend:
        address: "https://us-central1-ramnetquote.cloudfunctions.net"
      produces:
        - application/json
      responses:
        200:
          description: OK
paths:
  /quote:
    post:
      tags:
        - Quote
      summary: Create a new quote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuoteInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
    get:
      tags:
        - Quote
      summary: Get all quotes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
  /report:
    get:
      tags:
        - Quote
      summary: Get monthly quote report
      parameters:
        - name: year
          in: query
          description: Year to get report for
          required: true
          schema:
            type: integer
            format: int32
        - name: month
          in: query
          description: Month to get report for
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MonthlyQuoteReport'
  /quote/{id}:
    get:
      tags:
        - Quote
      summary: Get a quote by ID
      parameters:
        - name: id
          in: path
          description: ID of the quote to get
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
    put:
      tags:
        - Quote
      summary: Update a quote by ID
      parameters:
        - name: id
          in: path
          description: ID of the quote to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuoteInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
    delete:
      tags:
        - Quote
      summary: Delete a quote by ID
      parameters:
        - name: id
          in: path
          description: ID of the quote to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
components:
  schemas:
    Quote:
      type: object
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
        author:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - id
        - text
        - author
        - createdAt
        - updatedAt
    QuoteInput:
      type: object
      properties:
        text:
          type: string